const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  avatar: state => state.user.avatar,
  userInfo: state => state.user.userInfo,
  memberList: state => state.user.memberList,
  memberGroupList: state => state.user.memberGroupList,
  storeList: state => state.user.storeList,
  factoryList: state => state.user.factoryList,
  typeList: state => state.user.typeList,
  sortList: state => state.user.sortList,
  gradeList: state => state.user.gradeList,
  feeconfigList: state => state.user.feeconfigList,
  bankList: state => state.user.bankList,
  specList: state => state.user.specList,
  userList: state => state.user.userList,
  customerList: state => state.user.customerList,
  machtypeList: state => state.user.machtypeList,
  machineList: state => state.user.machineList,
  feetypeList: state => state.user.feetypeList,
  systemparmMap: state => state.user.systemparmMap,
  receivers: state => state.user.receivers,
  craners: state => state.user.craners,
  handors: state => state.user.handors,
  packRemarks: state => state.user.packRemarks,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  loadingDivs: state => state.loadingDiv.loadingDiv,
  // ==页面控制器
  pickUpGoodsPage: state => state.pageCtrl.pickUpGoods,
  transferStorePage: state => state.pageCtrl.transferStore
}
export default getters
